import Head from "next/head";
import Index from "@/styles/Index.module.css";

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={ Index.background }>Dotto</h1>
        <div id={ Index.main }>
          <h1 className={ Index.title }>Hey, I'm <span className={ Index.special }>Dotto</span>.</h1>
          <p className={ Index.paragraph }>I'm a <span className={ Index.special }>frontend</span> & <span className={ Index.special }>backend</span> developer from 🇮🇹.</p>
          <div id={ Index.cards }>
            <div className={ Index.card }>
              jpizza
            </div>
            <div className={ Index.card }></div>
          </div>
        </div>
      </main>
    </>
  );
}
